# Generated by Django 3.2.4 on 2021-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]