# Generated by Django 4.1.4 on 2023-01-16 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_code_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSignUp',
            fields=[
                ('campusSignUp', models.CharField(choices=[('Elon University', 'Elon University'), ('University of Maryland', 'University of Maryland')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocationSignUp',
            fields=[
                ('locationSignUp', models.CharField(choices=[('Elon, NC', 'Elon, NC'), ('Maryland', 'Maryland')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='propMgnr_admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropNameSignUp',
            fields=[
                ('propNameSignUp', models.CharField(choices=[('Oaks', 'Oaks'), ('Park Place', 'Park Place'), ('Mill Point', 'Mill Point')], max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
