# Generated by Django 4.1.4 on 2023-01-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_propmgnr_admin_propmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampusSignUp',
        ),
        migrations.DeleteModel(
            name='LocationSignUp',
        ),
        migrations.DeleteModel(
            name='PropNameSignUp',
        ),
        migrations.AddField(
            model_name='user',
            name='campusSignUp',
            field=models.CharField(choices=[('Elon', 'Elon'), ('UMD', 'UMD')], max_length=50, null=True),
        ),
    ]
