# Generated by Django 4.1.4 on 2023-01-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_campussignup_delete_locationsignup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campusSignUp',
            field=models.CharField(choices=[('Elon University', 'Elon University'), ('University of Maryland', 'University of Maryland')], max_length=50, null=True),
        ),
    ]
