# Generated by Django 4.1.4 on 2023-02-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_campussignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='campusSignUp',
            field=models.CharField(choices=[('PropertyName1', 'PropertyName1'), ('PropertyName2', 'PropertyName2')], max_length=50, null=True),
        ),
    ]
