# Generated by Django 4.1.4 on 2023-02-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_code_campussignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_PM_admin',
            field=models.BooleanField(default=False),
        ),
    ]
