# Generated by Django 4.1.4 on 2023-02-03 03:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_user_campussignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250, null=True)),
                ('location', models.CharField(choices=[('Elon NC', 'Elon NC'), ('College Park, MD', 'College Park, MD'), ('Burlington, NC', 'Burlington, NC'), ('Columbia, MD', 'Columbia, MD')], max_length=30, null=True)),
                ('name', models.CharField(default='any_name', max_length=200)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, upload_to=listings.models.get_image_filename)),
                ('url', models.URLField()),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Under Review'), (2, 'Approved'), (3, 'Rejected'), (4, 'Reported'), (5, 'CommMkt')], null=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Bedroom'), (2, 'Dining Room'), (3, 'Living Room'), (4, 'Office'), (5, 'Outdoor')], null=True)),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Used - Like New'), (3, 'Used - Good'), (4, 'Used - Fair')], null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('issue', models.CharField(blank=True, max_length=250, null=True)),
                ('itemsSold', models.IntegerField(default=0)),
                ('itemsUnSold', models.IntegerField(default=0)),
                ('percent_itemsSold', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('itemPrice', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('cover', models.ImageField(upload_to='images/')),
                ('publishing_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('swaptuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.swaptuser')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('paid', models.BooleanField(default='False')),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(default=None, max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Designates the name of the tag.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('payment_status', models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('F', 'failed')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(blank=True, to='listings.producttag'),
        ),
        migrations.CreateModel(
            name='CampusPropertyNamePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('Elon University', 'Elon University')], max_length=35, null=True)),
                ('propertyname', models.CharField(choices=[('Oaks', 'Oaks'), ('Park Place', 'Park Place'), ('Mill Point', 'Mill Point')], max_length=35)),
                ('confirmed', models.BooleanField(default=False)),
                ('Listings', models.ManyToManyField(to='listings.listing')),
            ],
        ),
    ]
