# Generated by Django 4.1.7 on 2023-03-06 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_propnamesignup_remove_code_campussignup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='banner_imgs/')),
                ('alt_text', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': '1. Banners',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brand_imgs/')),
            ],
            options={
                'verbose_name_plural': '3. Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CmntyListingsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cat_imgs/')),
            ],
            options={
                'verbose_name_plural': '2. Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '4. Colors',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='any_name', max_length=200)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, upload_to=listings.models.get_image_filename)),
                ('url', models.URLField()),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250, null=True)),
                ('color', models.CharField(choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Clear', 'Clear'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Multicolor', 'Multicolor'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=30, null=True)),
                ('location', models.CharField(choices=[('ElonNC', 'ElonNC'), ('CollegeParkMD', 'CollegeParkMD'), ('BurlingtonNC', 'BurlingtonNC'), ('ColumbiaMD', 'ColumbiaMD')], max_length=30, null=True)),
                ('delivery', models.PositiveSmallIntegerField(choices=[(1, 'Local Pickup'), (2, 'Swapt Delivery')], null=True)),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Under Review'), (2, 'Approved'), (3, 'Rejected'), (4, 'Reported'), (5, 'Closed')], null=True)),
                ('selling_stage', models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Pending'), (3, 'Sold')], null=True)),
                ('category', models.CharField(choices=[('Bedroom Furniture', 'Bedroom Furniture'), ('Dining Room Furniture', 'Dining Room Furniture'), ('Living Room Furniture', 'Living Room Furniture'), ('Office Furniture', 'Office Furniture'), ('Outdoor Furniture', 'Outdoor Furniture'), ('Other Furniture', 'Other Furniture')], max_length=50, null=True)),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Used - Like New'), (3, 'Used - Good'), (4, 'Used - Fair')], null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('issue', models.CharField(blank=True, max_length=250, null=True)),
                ('itemsSold', models.IntegerField(default=0)),
                ('itemsUnSold', models.IntegerField(default=0)),
                ('percent_itemsSold', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('itemPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cover', models.ImageField(upload_to='images/')),
                ('specs', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('publishing_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.brand')),
                ('categoryV3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.cmntylistingscategory')),
                ('swaptuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.swaptuser')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Designates the name of the tag.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '5. Sizes',
            },
        ),
        migrations.CreateModel(
            name='SwaptListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('paid', models.BooleanField(default='False')),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(default=None, max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='SwaptListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='any_name', max_length=200)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, upload_to=listings.models.get_image_filename)),
                ('url', models.URLField(default='anyurl.com')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='any_name', max_length=250)),
                ('description', models.CharField(max_length=250, null=True)),
                ('color', models.CharField(choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Clear', 'Clear'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Multicolor', 'Multicolor'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=30, null=True)),
                ('location', models.CharField(choices=[('ElonNC', 'ElonNC'), ('CollegeParkMD', 'CollegeParkMD'), ('BurlingtonNC', 'BurlingtonNC'), ('ColumbiaMD', 'ColumbiaMD')], max_length=30, null=True)),
                ('delivery', models.PositiveSmallIntegerField(choices=[(1, 'Local Pickup'), (2, 'Swapt Delivery')], null=True)),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Under Review'), (2, 'Approved'), (3, 'Rejected'), (4, 'Reported'), (5, 'Closed')], null=True)),
                ('selling_stage', models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Pending'), (3, 'Sold')], null=True)),
                ('category', models.CharField(choices=[('Bedroom Furniture', 'Bedroom Furniture'), ('Dining Room Furniture', 'Dining Room Furniture'), ('Living Room Furniture', 'Living Room Furniture'), ('Office Furniture', 'Office Furniture'), ('Outdoor Furniture', 'Outdoor Furniture'), ('Other Furniture', 'Other Furniture')], max_length=50, null=True)),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Used - Like New'), (3, 'Used - Good'), (4, 'Used - Fair')], null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('issue', models.CharField(blank=True, max_length=250, null=True)),
                ('itemsSold', models.IntegerField(default=0)),
                ('itemsUnSold', models.IntegerField(default=0)),
                ('percent_itemsSold', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('itemPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('publishing_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('categoryV2', models.ManyToManyField(related_name='swapt_item', to='listings.category')),
                ('listings', models.ManyToManyField(blank=True, related_name='order', to='listings.listing')),
                ('swaptuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.swaptuser')),
                ('tags', models.ManyToManyField(blank=True, to='listings.listingtag')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SwaptCampusPropertyNamePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('Elon', 'Elon'), ('UMD', 'UMD'), ('UNCG', 'UNCG')], default='Elon', max_length=30)),
                ('propertyname', models.CharField(choices=[('Oaks', 'Oaks'), ('MillPoint', 'MillPoint'), ('OakHill', 'OakHill')], max_length=30)),
                ('confirmed', models.BooleanField(default=False)),
                ('listings', models.ManyToManyField(to='listings.swaptlistingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Swapt_Bundle_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('swapt_bundle_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.swaptlistingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('payment_status', models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('F', 'failed')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='listing_imgs/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.color')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.size')),
            ],
            options={
                'verbose_name_plural': '7. ListingAttributes',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(blank=True, to='listings.listingtag'),
        ),
        migrations.CreateModel(
            name='CampusPropertyNamePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('Elon', 'Elon'), ('UMD', 'UMD'), ('UNCG', 'UNCG')], default='Elon', max_length=30)),
                ('propertyname', models.CharField(choices=[('Oaks', 'Oaks'), ('MillPoint', 'MillPoint'), ('OakHill', 'OakHill')], max_length=30)),
                ('confirmed', models.BooleanField(default=False)),
                ('listings', models.ManyToManyField(to='listings.listing')),
            ],
        ),
    ]
