# Generated by Django 4.1.4 on 2023-02-16 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_code_campussignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='any_name', max_length=200)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, upload_to=listings.models.get_image_filename)),
                ('url', models.URLField()),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250, null=True)),
                ('color', models.CharField(choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Clear', 'Clear'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Multicolor', 'Multicolor'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=30, null=True)),
                ('location', models.CharField(choices=[('ElonNC', 'ElonNC'), ('CollegeParkMD', 'CollegeParkMD'), ('BurlingtonNC', 'BurlingtonNC'), ('ColumbiaMD', 'ColumbiaMD')], max_length=30, null=True)),
                ('delivery', models.PositiveSmallIntegerField(choices=[(1, 'Local Pickup'), (2, 'Swapt Delivery')], null=True)),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Under Review'), (2, 'Approved'), (3, 'Rejected'), (4, 'Reported'), (5, 'Community')], null=True)),
                ('category', models.CharField(choices=[('Bedroom Furniture', 'Bedroom Furniture'), ('Dining Room Furniture', 'Dining Room Furniture'), ('Living Room Furniture', 'Living Room Furniture'), ('Office Furniture', 'Office Furniture'), ('Outdoor Furniture', 'Outdoor Furniture'), ('Other Furniture', 'Other Furniture')], max_length=50, null=True)),
                ('condition', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Used - Like New'), (3, 'Used - Good'), (4, 'Used - Fair')], null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('issue', models.CharField(blank=True, max_length=250, null=True)),
                ('itemsSold', models.IntegerField(default=0)),
                ('itemsUnSold', models.IntegerField(default=0)),
                ('percent_itemsSold', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('itemPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cover', models.ImageField(upload_to='images/')),
                ('publishing_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('categoryV2', models.ManyToManyField(related_name='item', to='listings.category')),
                ('swaptuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.swaptuser')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Designates the name of the tag.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwaptListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('paid', models.BooleanField(default='False')),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(default=None, max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='SwaptListingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('propertyname', models.CharField(blank=True, max_length=50)),
                ('campusname', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=15)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_shipped', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, upload_to=listings.models.get_image_filename)),
                ('category', models.CharField(choices=[('Bedroom Furniture', 'Bedroom Furniture'), ('Dining Room Furniture', 'Dining Room Furniture'), ('Living Room Furniture', 'Living Room Furniture'), ('Office Furniture', 'Office Furniture'), ('Outdoor Furniture', 'Outdoor Furniture'), ('Other Furniture', 'Other Furniture')], max_length=50, null=True)),
                ('listings', models.ManyToManyField(blank=True, related_name='order', to='listings.listing')),
                ('tags', models.ManyToManyField(blank=True, to='listings.listingtag')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('payment_status', models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('F', 'failed')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(blank=True, to='listings.listingtag'),
        ),
        migrations.CreateModel(
            name='CampusPropertyNamePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('ElonUniversity', 'ElonUniversity'), ('UMD', 'UMD'), ('UGA', 'UGA')], max_length=35, null=True)),
                ('propertyname', models.CharField(choices=[('Oaks', 'Oaks'), ('ParkPlace', 'ParkPlace'), ('MillPoint', 'MillPoint')], max_length=35)),
                ('confirmed', models.BooleanField(default=False)),
                ('listings', models.ManyToManyField(to='listings.listing')),
            ],
        ),
    ]
