# Generated by Django 4.1.4 on 2023-03-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
