# Generated by Django 4.1.4 on 2023-02-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='selling_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Pending'), (3, 'Sold')], null=True),
        ),
    ]
