# Generated by Django 4.1.4 on 2023-02-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTag',
            new_name='ListingTag',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='product',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='product',
            new_name='listing',
        ),
    ]
