# Generated by Django 4.1.7 on 2023-03-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmntylisting',
            name='desc',
            field=models.TextField(blank=True, verbose_name='desc'),
        ),
        migrations.AlterField(
            model_name='cmntylisting',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cmntylisting',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='swaptlistingmodel',
            name='desc',
            field=models.TextField(blank=True, verbose_name='desc'),
        ),
    ]
