# Generated by Django 4.1.7 on 2023-03-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categoryV2',
            field=models.ManyToManyField(related_name='item', to='listings.category'),
        ),
    ]
