# Generated by Django 4.1.4 on 2023-02-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_producttag_listingtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(choices=[(1, 'Beige'), (2, 'Black'), (3, 'Blue'), (4, 'Brown'), (5, 'Clear'), (6, 'Gold'), (7, 'Gray'), (8, 'Green'), (9, 'Multicolor'), (10, 'Orange'), (11, 'Pink'), (12, 'Purple'), (13, 'Red'), (14, 'Silver'), (15, 'White'), (16, 'Yellow')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery',
            field=models.CharField(choices=[(1, 'Local Pickup'), (2, 'Swapt Delivery')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bedroom Furniture'), (2, 'Dining Room Furniture'), (3, 'Living Room Furniture'), (4, 'Office Furniture'), (5, 'Outdoor Furniture'), (6, 'Other Furniture')], null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Under Review'), (2, 'Approved'), (3, 'Rejected'), (4, 'Reported'), (5, 'Community')], null=True),
        ),
    ]
