# Generated by Django 4.1.7 on 2023-02-26 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_selling_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swaptlistingmodel',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='swaptlistingmodel',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='campusname',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='is_shipped',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='listings',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='propertyname',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='street',
        ),
        migrations.RemoveField(
            model_name='swaptlistingmodel',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='categoryV2',
            field=models.ManyToManyField(related_name='swapt_item', to='listings.category'),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='color',
            field=models.CharField(choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Clear', 'Clear'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Multicolor', 'Multicolor'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Used - Like New'), (3, 'Used - Good'), (4, 'Used - Fair')], null=True),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='delivery',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Local Pickup'), (2, 'Swapt Delivery')], null=True),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='issue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='itemPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='itemsSold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='itemsUnSold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='location',
            field=models.CharField(choices=[('ElonNC', 'ElonNC'), ('CollegeParkMD', 'CollegeParkMD'), ('BurlingtonNC', 'BurlingtonNC'), ('ColumbiaMD', 'ColumbiaMD')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='percent_itemsSold',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='publishing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='selling_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Pending'), (3, 'Sold')], null=True),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Under Review'), (2, 'Approved'), (3, 'Rejected'), (4, 'Reported'), (5, 'Community')], null=True),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='title',
            field=models.CharField(default='any_name', max_length=250),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='url',
            field=models.URLField(default='anyurl.com'),
        ),
        migrations.AlterField(
            model_name='swaptlistingmodel',
            name='name',
            field=models.CharField(default='any_name', max_length=200),
        ),
    ]
