# Generated by Django 4.1.7 on 2023-02-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_swaptlistingmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedifficultypair',
            name='listings',
            field=models.ManyToManyField(to='listings.swaptlistingmodel'),
        ),
    ]
