# Generated by Django 4.1.4 on 2023-02-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_category_ordermodel_listing_categoryv2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[('Bedroom Furniture', 'Bedroom Furniture'), ('Dining Room Furniture', 'Dining Room Furniture'), ('Living Room Furniture', 'Living Room Furniture'), ('Office Furniture', 'Office Furniture'), ('Outdoor Furniture', 'Outdoor Furniture'), ('Other Furniture', 'Other Furniture')], null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(choices=[('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Clear', 'Clear'), ('Gold', 'Gold'), ('Gray', 'Gray'), ('Green', 'Green'), ('Multicolor', 'Multicolor'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Silver', 'Silver'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='delivery',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Local Pickup'), (2, 'Swapt Delivery')], null=True),
        ),
    ]
