# Generated by Django 4.1.4 on 2023-02-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_category_alter_listing_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Bedroom Furniture', 'Bedroom Furniture'), ('Dining Room Furniture', 'Dining Room Furniture'), ('Living Room Furniture', 'Living Room Furniture'), ('Office Furniture', 'Office Furniture'), ('Outdoor Furniture', 'Outdoor Furniture'), ('Other Furniture', 'Other Furniture')], max_length=50, null=True),
        ),
    ]
