# Generated by Django 4.1.7 on 2023-02-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_swaptlistingmodel_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuspropertynamepair',
            name='campus',
            field=models.CharField(choices=[('Elon', 'Elon'), ('UMD', 'UMD'), ('UNCG', 'UNCG')], default='Elon', max_length=30),
        ),
        migrations.AlterField(
            model_name='campuspropertynamepair',
            name='propertyname',
            field=models.CharField(choices=[('Oaks', 'Oaks'), ('MillPoint', 'MillPoint'), ('OakHill', 'OakHill')], max_length=30),
        ),
    ]
