# Generated by Django 4.1.4 on 2023-02-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_campuspropertynamepair_campus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwaptCampusPropertyNamePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('Elon', 'Elon'), ('UMD', 'UMD'), ('UNCG', 'UNCG')], default='Elon', max_length=30)),
                ('propertyname', models.CharField(choices=[('Oaks', 'Oaks'), ('MillPoint', 'MillPoint'), ('OakHill', 'OakHill')], max_length=30)),
                ('confirmed', models.BooleanField(default=False)),
                ('listings', models.ManyToManyField(to='listings.swaptlistingmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='GradeDifficultyPair',
        ),
    ]
